apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover-eadbox-sessions
  namespace: redis
spec:
  sentinel:
    replicas: 3
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - redis
  redis:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - redis
    securityContext:
      fsGroup: 0
    replicas: 3
    customConfig:
      - "maxmemory 4294967296"
      - "maxmemory-policy allkeys-lru"
    resources:
      limits:
        memory: 4Gi
    storage:
      keepAfterDeletion: true
      persistentVolumeClaim:
        metadata:
          name: redisfailover-eadbox-sessions-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
