apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover-eadbox-cache
  namespace: redis
spec:
  sentinel:
    replicas: 3
  redis:
    securityContext:
      fsGroup: 0
    replicas: 3
    customConfig:
      - "maxmemory 17179869184"
      - "maxmemory-policy allkeys-lru"
    storage:
      persistentVolumeClaim:
        metadata:
          name: redisfailover-eadbox-cache-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 16Gi
