apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover-eadbox-resque
  namespace: redis
spec:
  sentinel:
    replicas: 3
  redis:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-nodepool
              operator: In
              values:
              - redis
    securityContext:
      fsGroup: 0
    replicas: 3
    customConfig:
      - "maxmemory 17179869184"
      - "maxmemory-policy allkeys-lru"
    resources:
      requests:
        memory: 8Gi
      limits:
        memory: 16Gi
    storage:
      keepAfterDeletion: true
      persistentVolumeClaim:
        metadata:
          name: redisfailover-eadbox-resque-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 16Gi
