apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover-eadbox-cache
  namespace: redis
spec:
  sentinel:
    replicas: 3
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - redis
  redis:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - redis
    securityContext:
      fsGroup: 0
    replicas: 5
    customConfig:
      - "maxmemory 11811160064"
      - "maxmemory-policy allkeys-lru"
    resources:
      requests:
        memory: 12Gi
    storage:
      keepAfterDeletion: false
      persistentVolumeClaim:
        metadata:
          name: redisfailover-eadbox-cache-data-new
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 16Gi
