apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover-eadbox-affiliates
  namespace: redis
spec:
  sentinel:
    replicas: 3
  redis:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-nodepool
              operator: In
              values:
              - redis
    securityContext:
      fsGroup: 0
    replicas: 3
    customConfig:
      - "maxmemory 536870912"
      - "maxmemory-policy allkeys-lru"
    storage:
      persistentVolumeClaim:
        metadata:
          name: redisfailover-eadbox-affiliates-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 512Mi
